package fr.esgi.myappointments.business;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
import java.util.Date;

import android.os.Parcel;
import android.os.Parcelable;
// KEEP INCLUDES END
/**
 * Entity mapped to table ADDRESS.
 */
public class Address implements Parcelable {

    private Long id;
    private Integer serverId;
    private String country;
    /** Not-null value. */
    private String zipcode;
    /** Not-null value. */
    private String city;
    private String street;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Address() {
    }

    public Address(Long id) {
        this.id = id;
    }

    public Address(Long id, Integer serverId, String country, String zipcode, String city, String street) {
        this.id = id;
        this.serverId = serverId;
        this.country = country;
        this.zipcode = zipcode;
        this.city = city;
        this.street = street;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getServerId() {
        return serverId;
    }

    public void setServerId(Integer serverId) {
        this.serverId = serverId;
    }

    public String getCountry() {
        return country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    /** Not-null value. */
    public String getZipcode() {
        return zipcode;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setZipcode(String zipcode) {
        this.zipcode = zipcode;
    }

    /** Not-null value. */
    public String getCity() {
        return city;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCity(String city) {
        this.city = city;
    }

    public String getStreet() {
        return street;
    }

    public void setStreet(String street) {
        this.street = street;
    }

    // KEEP METHODS - put your custom methods here
    public static final Parcelable.Creator<Address> CREATOR = new Parcelable.Creator<Address>() {
		@Override
		public Address createFromParcel(Parcel in) {
			return new Address(in);
		}

		@Override
		public Address[] newArray(int size) {
			return new Address[size];
		}
	};
	
	private Address(Parcel in) {
		readFromParcel(in);
	}
	
    @Override
    public int describeContents() {
    	return 0;
    }
    
    @Override
	public void writeToParcel(Parcel dest, int flags) {
		dest.writeLong(id);
		dest.writeInt(serverId);
		dest.writeString(country);
		dest.writeString(zipcode);
		dest.writeString(city);
		dest.writeString(street);
	}

	public void readFromParcel(Parcel in) {
		id = in.readLong();
		serverId = in.readInt();
		country = in.readString();
		zipcode = in.readString();
		city = in.readString();
		street = in.readString();
	}
    // KEEP METHODS END

}
