<<<<<<< HEAD
package fr.esgi.myappointments.business;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
import java.util.Date;
import android.os.Parcel;
import android.os.Parcelable;
// KEEP INCLUDES END
/**
 * Entity mapped to table COMPANY.
 */
public class Company implements Parcelable {

    private Long id;
    private Integer uniqueID;
    private String sirenID;
    /** Not-null value. */
    private String companyName;
    /** Not-null value. */
    private String contactFirstname;
    /** Not-null value. */
    private String contactLastname;
    /** Not-null value. */
    private String address;
    /** Not-null value. */
    private String email;
    /** Not-null value. */
    private String phone;
    private java.util.Date creationDate;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Company() {
    }

    public Company(Long id) {
        this.id = id;
    }

    public Company(Long id, Integer uniqueID, String sirenID, String companyName, String contactFirstname, String contactLastname, String address, String email, String phone, java.util.Date creationDate) {
        this.id = id;
        this.uniqueID = uniqueID;
        this.sirenID = sirenID;
        this.companyName = companyName;
        this.contactFirstname = contactFirstname;
        this.contactLastname = contactLastname;
        this.address = address;
        this.email = email;
        this.phone = phone;
        this.creationDate = creationDate;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getUniqueID() {
        return uniqueID;
    }

    public void setUniqueID(Integer uniqueID) {
        this.uniqueID = uniqueID;
    }

    public String getSirenID() {
        return sirenID;
    }

    public void setSirenID(String sirenID) {
        this.sirenID = sirenID;
    }

    /** Not-null value. */
    public String getCompanyName() {
        return companyName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    /** Not-null value. */
    public String getContactFirstname() {
        return contactFirstname;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setContactFirstname(String contactFirstname) {
        this.contactFirstname = contactFirstname;
    }

    /** Not-null value. */
    public String getContactLastname() {
        return contactLastname;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setContactLastname(String contactLastname) {
        this.contactLastname = contactLastname;
    }

    /** Not-null value. */
    public String getAddress() {
        return address;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAddress(String address) {
        this.address = address;
    }

    /** Not-null value. */
    public String getEmail() {
        return email;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setEmail(String email) {
        this.email = email;
    }

    /** Not-null value. */
    public String getPhone() {
        return phone;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    public java.util.Date getCreationDate() {
        return creationDate;
    }

    public void setCreationDate(java.util.Date creationDate) {
        this.creationDate = creationDate;
    }

    // KEEP METHODS - put your custom methods here
    public static final Parcelable.Creator<Company> CREATOR = new Parcelable.Creator<Company>() {
		@Override
		public Company createFromParcel(Parcel in) {
			return new Company(in);
		}

		@Override
		public Company[] newArray(int size) {
			return new Company[size];
		}
	};
	
	private Company(Parcel in) {
		readFromParcel(in);
	}
	
    @Override
    public int describeContents() {
    	return 0;
    }
    
    @Override
	public void writeToParcel(Parcel dest, int flags) {
		dest.writeLong(id);
		dest.writeInt(uniqueID);
		dest.writeString(sirenID);
		dest.writeString(companyName);
		dest.writeString(contactFirstname);
		dest.writeString(contactLastname);
		dest.writeString(address);
		dest.writeString(email);
		dest.writeString(phone);
		dest.writeLong((creationDate != null) ? creationDate.getTime() : 0);
	}

	public void readFromParcel(Parcel in) {
		id = in.readLong();
		uniqueID = in.readInt();
		sirenID = in.readString();
		companyName = in.readString();
		contactFirstname = in.readString();
		contactLastname = in.readString();
		address = in.readString();
		email = in.readString();
		phone = in.readString();
		creationDate = new Date(in.readLong());
		
	}
    // KEEP METHODS END

}
=======
package fr.esgi.myappointments.business;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
import java.util.Date;
import android.os.Parcel;
import android.os.Parcelable;
// KEEP INCLUDES END
/**
 * Entity mapped to table COMPANY.
 */
public class Company implements Parcelable {

    private Long id;
    private Integer uniqueID;
    private String sirenID;
    /** Not-null value. */
    private String companyName;
    /** Not-null value. */
    private String contactFirstname;
    /** Not-null value. */
    private String contactLastname;
    /** Not-null value. */
    private String address;
    /** Not-null value. */
    private String email;
    /** Not-null value. */
    private String phone;
    private java.util.Date creationDate;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Company() {
    }

    public Company(Long id) {
        this.id = id;
    }

    public Company(Long id, Integer uniqueID, String sirenID, String companyName, String contactFirstname, String contactLastname, String address, String email, String phone, java.util.Date creationDate) {
        this.id = id;
        this.uniqueID = uniqueID;
        this.sirenID = sirenID;
        this.companyName = companyName;
        this.contactFirstname = contactFirstname;
        this.contactLastname = contactLastname;
        this.address = address;
        this.email = email;
        this.phone = phone;
        this.creationDate = creationDate;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getUniqueID() {
        return uniqueID;
    }

    public void setUniqueID(Integer uniqueID) {
        this.uniqueID = uniqueID;
    }

    public String getSirenID() {
        return sirenID;
    }

    public void setSirenID(String sirenID) {
        this.sirenID = sirenID;
    }

    /** Not-null value. */
    public String getCompanyName() {
        return companyName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    /** Not-null value. */
    public String getContactFirstname() {
        return contactFirstname;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setContactFirstname(String contactFirstname) {
        this.contactFirstname = contactFirstname;
    }

    /** Not-null value. */
    public String getContactLastname() {
        return contactLastname;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setContactLastname(String contactLastname) {
        this.contactLastname = contactLastname;
    }

    /** Not-null value. */
    public String getAddress() {
        return address;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAddress(String address) {
        this.address = address;
    }

    /** Not-null value. */
    public String getEmail() {
        return email;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setEmail(String email) {
        this.email = email;
    }

    /** Not-null value. */
    public String getPhone() {
        return phone;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    public java.util.Date getCreationDate() {
        return creationDate;
    }

    public void setCreationDate(java.util.Date creationDate) {
        this.creationDate = creationDate;
    }

    // KEEP METHODS - put your custom methods here
    public static final Parcelable.Creator<Company> CREATOR = new Parcelable.Creator<Company>() {
		@Override
		public Company createFromParcel(Parcel in) {
			return new Company(in);
		}

		@Override
		public Company[] newArray(int size) {
			return new Company[size];
		}
	};
	
	private Company(Parcel in) {
		readFromParcel(in);
	}
	
    @Override
    public int describeContents() {
    	return 0;
    }
    
    @Override
	public void writeToParcel(Parcel dest, int flags) {
		dest.writeLong(id);
		dest.writeInt(uniqueID);
		dest.writeString(sirenID);
		dest.writeString(companyName);
		dest.writeString(contactFirstname);
		dest.writeString(contactLastname);
		dest.writeString(address);
		dest.writeString(email);
		dest.writeString(phone);
		dest.writeLong((creationDate != null) ? creationDate.getTime() : 0);
	}

	public void readFromParcel(Parcel in) {
		id = in.readLong();
		uniqueID = in.readInt();
		sirenID = in.readString();
		companyName = in.readString();
		contactFirstname = in.readString();
		contactLastname = in.readString();
		address = in.readString();
		email = in.readString();
		phone = in.readString();
		creationDate = new Date(in.readLong());
		
	}
    // KEEP METHODS END

}
>>>>>>> 72189d4570307a88d241475477cdc67293633d92
