package fr.esgi.myappointments.business;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
import java.util.Date;
import android.os.Parcel;
import android.os.Parcelable;
// KEEP INCLUDES END
/**
 * Entity mapped to table USER.
 */
public class User implements Parcelable {

    private Long id;
    private Integer uniqueID;
    /** Not-null value. */
    private String firstname;
    /** Not-null value. */
    private String lastname;
    /** Not-null value. */
    private String phone;
    /** Not-null value. */
    private String email;
    private String password;
    private java.util.Date creationDate;
    private java.util.Date birthDate;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public User() {
    }

    public User(Long id) {
        this.id = id;
    }

    public User(Long id, Integer uniqueID, String firstname, String lastname, String phone, String email, String password, java.util.Date creationDate, java.util.Date birthDate) {
        this.id = id;
        this.uniqueID = uniqueID;
        this.firstname = firstname;
        this.lastname = lastname;
        this.phone = phone;
        this.email = email;
        this.password = password;
        this.creationDate = creationDate;
        this.birthDate = birthDate;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getUniqueID() {
        return uniqueID;
    }

    public void setUniqueID(Integer uniqueID) {
        this.uniqueID = uniqueID;
    }

    /** Not-null value. */
    public String getFirstname() {
        return firstname;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    /** Not-null value. */
    public String getLastname() {
        return lastname;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    /** Not-null value. */
    public String getPhone() {
        return phone;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /** Not-null value. */
    public String getEmail() {
        return email;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setEmail(String email) {
        this.email = email;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public java.util.Date getCreationDate() {
        return creationDate;
    }

    public void setCreationDate(java.util.Date creationDate) {
        this.creationDate = creationDate;
    }

    public java.util.Date getBirthDate() {
        return birthDate;
    }

    public void setBirthDate(java.util.Date birthDate) {
        this.birthDate = birthDate;
    }

    // KEEP METHODS - put your custom methods here
    public static final Parcelable.Creator<User> CREATOR = new Parcelable.Creator<User>() {
		@Override
		public User createFromParcel(Parcel in) {
			return new User(in);
		}

		@Override
		public User[] newArray(int size) {
			return new User[size];
		}
	};
	
	private User(Parcel in) {
		readFromParcel(in);
	}
	
    @Override
    public int describeContents() {
    	return 0;
    }
    
    @Override
   	public void writeToParcel(Parcel dest, int flags) {
   		dest.writeLong(id);
   		dest.writeInt(uniqueID);
   		dest.writeString(firstname);
   		dest.writeString(lastname);
   		dest.writeString(email);
   		dest.writeString(phone);
   		dest.writeLong((creationDate != null) ? creationDate.getTime() : 0);
   		dest.writeLong((birthDate != null) ? birthDate.getTime() : 0);
   	}

   	public void readFromParcel(Parcel in) {
   		id = in.readLong();
   		uniqueID = in.readInt();
   		firstname = in.readString();
   		lastname = in.readString();
   		email = in.readString();
   		phone = in.readString();
   		creationDate = new Date(in.readLong());
   		birthDate = new Date(in.readLong());
   	}
    // KEEP METHODS END

}
